// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in repro/ent/runtime.go

const (
	Version = "v0.6.1-0.20210302154252-3a64e2d20d1c"            // Version of ent codegen.
	Sum     = "h1:RkfBTds/00CX0XAvA10MhwcZe9nDcup375yu8EJQ4zc=" // Sum of ent codegen.
)
