// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"repro/ent/role"
	"repro/ent/user"
	"repro/ent/userrole"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// UserRole is the model entity for the UserRole schema.
type UserRole struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TargetID holds the value of the "target_id" field.
	TargetID int `json:"target_id,omitempty"`
	// TargetType holds the value of the "target_type" field.
	TargetType string `json:"target_type,omitempty"`
	// ActorType holds the value of the "actor_type" field.
	ActorType string `json:"actor_type,omitempty"`
	// ActorID holds the value of the "actor_id" field.
	ActorID int `json:"actor_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserRoleQuery when eager-loading is set.
	Edges   UserRoleEdges `json:"edges"`
	role_id *int
}

// UserRoleEdges holds the relations/edges for other nodes in the graph.
type UserRoleEdges struct {
	// Role holds the value of the role edge.
	Role *Role `json:"role,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// RoleOrErr returns the Role value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserRoleEdges) RoleOrErr() (*Role, error) {
	if e.loadedTypes[0] {
		if e.Role == nil {
			// The edge role was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: role.Label}
		}
		return e.Role, nil
	}
	return nil, &NotLoadedError{edge: "role"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserRoleEdges) UserOrErr() (*User, error) {
	if e.loadedTypes[1] {
		if e.User == nil {
			// The edge user was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserRole) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case userrole.FieldID, userrole.FieldTargetID, userrole.FieldActorID:
			values[i] = &sql.NullInt64{}
		case userrole.FieldTargetType, userrole.FieldActorType:
			values[i] = &sql.NullString{}
		case userrole.ForeignKeys[0]: // role_id
			values[i] = &sql.NullInt64{}
		default:
			return nil, fmt.Errorf("unexpected column %q for type UserRole", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserRole fields.
func (ur *UserRole) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userrole.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ur.ID = int(value.Int64)
		case userrole.FieldTargetID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field target_id", values[i])
			} else if value.Valid {
				ur.TargetID = int(value.Int64)
			}
		case userrole.FieldTargetType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_type", values[i])
			} else if value.Valid {
				ur.TargetType = value.String
			}
		case userrole.FieldActorType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor_type", values[i])
			} else if value.Valid {
				ur.ActorType = value.String
			}
		case userrole.FieldActorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field actor_id", values[i])
			} else if value.Valid {
				ur.ActorID = int(value.Int64)
			}
		case userrole.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field role_id", value)
			} else if value.Valid {
				ur.role_id = new(int)
				*ur.role_id = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryRole queries the "role" edge of the UserRole entity.
func (ur *UserRole) QueryRole() *RoleQuery {
	return (&UserRoleClient{config: ur.config}).QueryRole(ur)
}

// QueryUser queries the "user" edge of the UserRole entity.
func (ur *UserRole) QueryUser() *UserQuery {
	return (&UserRoleClient{config: ur.config}).QueryUser(ur)
}

// Update returns a builder for updating this UserRole.
// Note that you need to call UserRole.Unwrap() before calling this method if this UserRole
// was returned from a transaction, and the transaction was committed or rolled back.
func (ur *UserRole) Update() *UserRoleUpdateOne {
	return (&UserRoleClient{config: ur.config}).UpdateOne(ur)
}

// Unwrap unwraps the UserRole entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ur *UserRole) Unwrap() *UserRole {
	tx, ok := ur.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserRole is not a transactional entity")
	}
	ur.config.driver = tx.drv
	return ur
}

// String implements the fmt.Stringer.
func (ur *UserRole) String() string {
	var builder strings.Builder
	builder.WriteString("UserRole(")
	builder.WriteString(fmt.Sprintf("id=%v", ur.ID))
	builder.WriteString(", target_id=")
	builder.WriteString(fmt.Sprintf("%v", ur.TargetID))
	builder.WriteString(", target_type=")
	builder.WriteString(ur.TargetType)
	builder.WriteString(", actor_type=")
	builder.WriteString(ur.ActorType)
	builder.WriteString(", actor_id=")
	builder.WriteString(fmt.Sprintf("%v", ur.ActorID))
	builder.WriteByte(')')
	return builder.String()
}

// UserRoles is a parsable slice of UserRole.
type UserRoles []*UserRole

func (ur UserRoles) config(cfg config) {
	for _i := range ur {
		ur[_i].config = cfg
	}
}
