// Code generated by entc, DO NOT EDIT.

package spec

const (
	// Label holds the string label denoting the spec type in the database.
	Label = "spec"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// Table holds the table name of the spec in the database.
	Table = "specs"
)

// Columns holds all SQL columns for spec fields.
var Columns = []string{
	FieldID,
}
