// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Spec is the predicate function for spec builders.
type Spec func(*sql.Selector)
